const PROJECT_FIELDS = {
  projectId: "JPI_Project_ID",
  projectName: "JPI_Project_Name",
  description: "JPI_Project_Description",
  priority: "JPI_Priority",
  onOpsList: "JPI_On_Opp_List",
  deadline: "JPI_Deadline_date",
  firstContactDate: "JPI_First_Contact_date",
  status: "JPI_Status",
  alias: "JPI_Alias",
  implemented: "JPI_Implemented",
  waitingOn: "JPI_Waiting_on_Contact",
  waitingFor: "JPI_Waiting_For",
  assignedTo: "JPI_Assigned_To",
  clientMinistry: "JPI_Client_Ministry",
  folderName: "JPI_Folder_Name",
  intakeFormStatus: "JPI_Intake_From_Status",
  lastComm: "JPI_Last_Comm_date",
  fundingSource: "JPI_Funding_Source",
  locationId: "JPI_Location_ID",
  projectSponsor: "JPI_Project_Sponsor",
  ministry: "JPI_Ministry",
  division: "JPI_Division",
  branch: "JPI_Branch",
  requestedCompletionDate: "JPI_Requested_Completion_Date",
  assignedToPM: "JPI_Assigned_to_PM",
  dateAdded: "JPI_Trans_Insert_TS",
};

module.exports = PROJECT_FIELDS;
