openapi: 3.0.0
info:
  title: My API
  version: 1.0.0
servers:
  - url: http://localhost:3001/backend-api
paths:
  /projects:
    $ref: "./paths/projects/index.yaml"
  /projects/{id}:
    $ref: "./paths/projects/id.yaml"
  /projects/searchIds:
    $ref: "./paths/projects/searchIds.yaml"
  /users:
    $ref: "./paths/users/index.yaml"
  /users/login:
    $ref: "./paths/users/azureLogin.yaml"
  /users/searchNames:
    $ref: "./paths/users/searchNames.yaml"
  /locations:
    $ref: "./paths/locations.yaml"
  /organizations:
    $ref: "./paths/organizations.yaml"
  /dropdowns:
    $ref: "./paths/dropdowns.yaml"
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Project:
      $ref: "./schemas/Project.yaml"
    User:
      $ref: "./schemas/User.yaml"
    Location:
      $ref: "./schemas/Location.yaml"
